import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="flex flex-col h-screen justify-between bg-materialUI-LightOnPrimary dark:bg-materialUI-DarkOnPrimary"
        style={{ height: "-webkit-fill-available" }}
      >
        <div className="py-2 mb-auto bg-materialUI-LightOnPrimary dark:bg-materialUI-DarkOnPrimary ">
          {children}
        </div>
      </body>
    </html>
  );
}
